// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO_GjDJDkBSgM46wqcc3zMkn1J3URTphc',
    appId: '1:911073199377:web:b548a1ac148332288d38b0',
    messagingSenderId: '911073199377',
    projectId: 'mygardeningapp-afc3f',
    authDomain: 'mygardeningapp-afc3f.firebaseapp.com',
    storageBucket: 'mygardeningapp-afc3f.appspot.com',
    measurementId: 'G-R7VKMH7H3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARHoOXoJUiw8DjfUimX1ZH9PD0VvkuSEg',
    appId: '1:911073199377:android:ba451ab3840fb2918d38b0',
    messagingSenderId: '911073199377',
    projectId: 'mygardeningapp-afc3f',
    storageBucket: 'mygardeningapp-afc3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQkt3jsHE1DKDyljr-o19TUKDAICiL8y4',
    appId: '1:911073199377:ios:442e11cd7f340e7f8d38b0',
    messagingSenderId: '911073199377',
    projectId: 'mygardeningapp-afc3f',
    storageBucket: 'mygardeningapp-afc3f.appspot.com',
    iosClientId: '911073199377-44nb5rkj88pcru93oj7ba096ehbs92po.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGardeningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQkt3jsHE1DKDyljr-o19TUKDAICiL8y4',
    appId: '1:911073199377:ios:442e11cd7f340e7f8d38b0',
    messagingSenderId: '911073199377',
    projectId: 'mygardeningapp-afc3f',
    storageBucket: 'mygardeningapp-afc3f.appspot.com',
    iosClientId: '911073199377-44nb5rkj88pcru93oj7ba096ehbs92po.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGardeningApp',
  );
}
